apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-cifu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0046-tenant/tkrw-pr712-0075-0046-app/devfile-sample-cifu@sha256:067e0c8cc78532544cc1849a97f2201ee9983639e98c03db1a494abfe37b72cd
        name: my-nodejs
        resources: {}
status: {}
